import { expect, test } from '@playwright/test'

test('empty depth view opens the official Odra chart without inventing depths', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: '3D', exact: true }).click()
  await page.getByRole('button', { name: 'Карты глубин Одры', exact: true }).click()
  const sheet = page.getByRole('dialog', { name: 'Карты Одры · Щецин' })
  await expect(sheet.getByRole('link', { name: /Скачать официальный лист/ })).toHaveAttribute('href', 'https://www.szczecin.uzs.gov.pl/wp-content/uploads/2026/05/P17OD735.zip')
  await expect(sheet).toContainText('этот ENC здесь ещё не отображается')
})

test('depth canvas selects observations and rotates the 3D view by dragging', async ({ page }) => {
  await page.goto('journal')
  await page.locator('details[aria-label="Точки глубин"] > summary').click()
  await page.getByRole('textbox', { name: 'Название набора' }).fill('Проверка рельефа')
  await page.getByRole('textbox', { name: 'Источник', exact: true }).fill('Контрольные точки')
  await page.getByRole('textbox', { name: 'Вертикальный датум' }).fill('Ноль теста')
  const features = [[14.619, 53.3866, 2.4], [14.6192, 53.3866, 2.9], [14.6191, 53.3868, 3.1]].map(([lon, lat, depthM]) => ({ type: 'Feature', geometry: { type: 'Point', coordinates: [lon, lat] }, properties: { depthM } }))
  await page.locator('input[type="file"][accept*=".geojson"]').setInputFiles({ name: 'depth.geojson', mimeType: 'application/geo+json', buffer: Buffer.from(JSON.stringify({ type: 'FeatureCollection', features })) })
  await page.getByRole('button', { name: 'Сохранить точки' }).click()
  await expect(page.getByText('Карта глубин сохранена локально.')).toBeVisible()
  await page.goto('./')
  await page.getByRole('button', { name: '3D', exact: true }).click()
  await page.getByRole('button', { name: 'Настройки рельефа' }).click()
  let sheet = page.getByRole('dialog', { name: 'Настройки рельефа' })
  await sheet.getByRole('radio', { name: 'Проверка рельефа' }).check()
  await sheet.getByRole('button', { name: 'Закрыть', exact: true }).click()
  const plot = page.locator('canvas.map-bottom__plot')
  await expect(plot).toBeVisible()
  await plot.focus()
  await plot.press('Enter')
  await expect(page.locator('.depth-explorer__point')).toContainText('2.4 м')
  await expect(page.locator('.depth-explorer__point')).toContainText('Контрольные точки')
  await page.getByRole('button', { name: 'Закрыть глубину' }).click()
  await page.getByRole('button', { name: 'Настройки рельефа' }).click()
  sheet = page.getByRole('dialog', { name: 'Настройки рельефа' })
  await sheet.getByRole('radio', { name: '3D схема' }).check()
  await expect(sheet.getByRole('slider', { name: /Поворот схемы/ })).toHaveValue('35')
  await sheet.getByRole('button', { name: 'Закрыть', exact: true }).click()
  const bounds = await plot.boundingBox()
  if (!bounds) throw new Error('Depth canvas unavailable')
  await page.mouse.move(bounds.x + bounds.width * .35, bounds.y + bounds.height * .5)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width * .65, bounds.y + bounds.height * .5, { steps: 6 })
  await page.mouse.up()
  await expect(page.locator('.depth-explorer__point')).toHaveCount(0)
  await page.getByRole('button', { name: 'Настройки рельефа' }).click()
  await expect(sheet.getByRole('slider', { name: /Поворот схемы/ })).not.toHaveValue('35')
})
