import { expect, test } from '@playwright/test'
import { pathToFileURL } from 'node:url'

test('exported HTML opens offline, edits the same journal and can export a new copy', async ({ page, context }, testInfo) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Начать промер' }).click()
  await page.getByRole('button', { name: 'Пропустить таймер' }).click()
  await page.getByRole('button', { name: 'Добавить пять оборотов ручки' }).click()
  await page.getByRole('button', { name: 'Закончить промер' }).click()
  await page.getByRole('checkbox', { name: /Вся леска/ }).check()
  await page.getByRole('button', { name: 'Сохранить заброс' }).click()
  await expect(page.getByText('Заброс сохранён на этом устройстве.')).toBeVisible()
  await page.goto('journal')
  await page.locator('details[aria-label="Перенос данных"] > summary').click()
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Автономный HTML' }).click()
  const file = testInfo.outputPath('marker.html')
  await (await downloaded).saveAs(file)
  await context.setOffline(true)
  const portable = await context.newPage()
  const errors: string[] = []
  portable.on('pageerror', error => errors.push(error.message))
  await portable.goto(pathToFileURL(file).href)
  await expect(portable.getByRole('button', { name: 'Начать промер' })).toBeVisible()
  await portable.getByRole('button', { name: 'Журнал', exact: true }).click()
  await portable.getByRole('button', { name: 'Открыть', exact: true }).click()
  await expect(portable.getByText(/Выбрано ≈ 4.0 м лески/)).toBeVisible()
  await portable.getByRole('textbox', { name: 'Заметка', exact: true }).fill('Изменено в автономной копии')
  await portable.getByRole('button', { name: 'Сохранить', exact: true }).click()
  await portable.getByRole('button', { name: 'Закрыть' }).click()
  await expect(portable.getByRole('status').filter({ hasText: 'Изменения сохранены' })).toBeVisible()
  await portable.locator('details[aria-label="Перенос данных"] > summary').click()
  const redownloaded = portable.waitForEvent('download')
  await portable.getByRole('button', { name: 'Автономный HTML' }).click()
  const secondFile = testInfo.outputPath('marker-edited.html')
  await (await redownloaded).saveAs(secondFile)
  await portable.goto(pathToFileURL(secondFile).href)
  await portable.getByRole('button', { name: 'Журнал', exact: true }).click()
  await portable.getByRole('button', { name: 'Открыть', exact: true }).click()
  await expect(portable.getByRole('textbox', { name: 'Заметка', exact: true })).toHaveValue('Изменено в автономной копии')
  expect(errors).toEqual([])
  await page.goto('journal')
  await page.locator('details[aria-label="Перенос данных"] > summary').click()
  await page.locator('input[type="file"][accept*=".html"]').setInputFiles(secondFile)
  await expect(page.getByText('Копия готова к добавлению')).toBeVisible()
  await page.getByRole('button', { name: 'Импортировать копиями' }).click()
  await expect(page.locator('.journal-session')).toHaveCount(2)
})
