import { expect, test } from '@playwright/test'

test('a calibrated cast survives reload with turns, mark, and confirmed line length', async ({ page }) => {
  await page.goto('./')
  await expect(page.getByRole('button', { name: 'Начать промер' })).toBeVisible()

  await page.getByRole('button', { name: /Заброс #1/ }).click()
  await page.getByRole('button', { name: 'Новая сессия' }).click()
  await page.getByRole('button', { name: /Катушка:.*80 см\/об\./ }).click()
  await page.getByRole('textbox', { name: 'Длина лески, м' }).fill('40')
  await page.getByRole('textbox', { name: 'Обороты ручки' }).fill('50')
  await page.getByRole('button', { name: 'Сохранить калибровку' }).click()
  await expect(page.getByRole('button', { name: /Катушка: 80 см\/об\./ })).toBeVisible()

  await page.locator('.survey-metric').nth(1).click()
  await page.getByRole('textbox', { name: /Угол от ориентира/ }).fill('12')
  await page.getByRole('button', { name: 'Использовать угол' }).click()
  await expect(page.locator('svg .sector-preview')).toBeVisible()
  await page.getByRole('button', { name: 'Начать промер' }).click()
  await page.getByRole('button', { name: 'Коснулся воды' }).click()
  await expect(page.getByRole('timer')).toBeVisible()
  await page.getByRole('button', { name: /Дно · остановить/ }).click()
  await expect(page.locator('.survey-counter-value')).toBeVisible()

  await page.getByRole('button', { name: 'Добавить пять оборотов ручки' }).click()
  await expect(page.locator('.survey-counter-value strong')).toHaveText('5')
  await page.getByRole('button', { name: 'Трава' }).click()
  await expect(page.getByText(/Трава · 5 об/)).toBeVisible()
  await page.getByRole('button', { name: 'Добавить пять оборотов ручки' }).click()
  await expect(page.locator('.survey-counter-value strong')).toHaveText('10')
  await page.getByRole('button', { name: 'Закончить промер' }).click()
  await page.getByRole('checkbox', { name: 'Вся леска выбрана и вся подмотка посчитана' }).check()
  await expect(page.getByRole('dialog').getByText(/≈ 8 м лески по оборотам/)).toBeVisible()
  await page.getByRole('button', { name: 'Сохранить заброс' }).click()
  await expect(page.getByText('Заброс сохранён на этом устройстве.')).toBeVisible()
  const pngDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать схему PNG' }).click()
  const download = await pngDownload
  expect(download.suggestedFilename()).toMatch(/^marker-sector-\d{4}-\d{2}-\d{2}\.png$/)
  expect(await download.failure()).toBeNull()

  await page.getByRole('link', { name: 'Журнал' }).click()
  await page.getByRole('button', { name: 'Открыть', exact: true }).click()
  await expect(page.getByText(/Выбрано ≈ 8\.0 м лески/)).toBeVisible()
  await expect(page.getByText('5 об. · Трава')).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Открыть', exact: true }).click()
  await expect(page.getByText(/Выбрано ≈ 8\.0 м лески/)).toBeVisible()
  await expect(page.getByText('5 об. · Трава')).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть' }).click()
  await page.getByRole('button', { name: 'Повторить' }).click()
  await page.getByRole('link', { name: 'Промер', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Коснулся воды' })).toBeVisible()
  await expect(page.getByText(/#2 · 12°/)).toBeVisible()
  await page.getByRole('button', { name: 'Пропустить таймер' }).click()
  await expect(page.locator('.survey-counter-value strong')).toHaveText('0')
  await expect(page.locator('.survey-mark-list li')).toHaveCount(0)
})

test('fall interrupted by navigation or reload keeps draft; partial retrieval keeps distance unknown', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Начать промер' }).click()
  await page.getByRole('button', { name: 'Коснулся воды' }).click()
  await expect(page.getByRole('timer')).toBeVisible()
  await page.getByRole('link', { name: 'Журнал' }).click()
  await page.getByRole('link', { name: 'Промер' }).click()
  await expect(page.getByText('Время падения не сохранено. Обороты и отметки на месте.')).toBeVisible()

  await page.getByRole('button', { name: 'Повторить падение' }).click()
  await page.getByRole('button', { name: 'Коснулся воды' }).click()
  await expect(page.getByRole('timer')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Время падения не сохранено. Обороты и отметки на месте.')).toBeVisible()

  await page.getByRole('button', { name: 'Продолжить без времени' }).click()
  await page.getByRole('button', { name: 'Добавить пять оборотов ручки' }).click()
  await expect(page.locator('.survey-counter-value strong')).toHaveText('5')
  await page.getByRole('button', { name: 'Закончить промер' }).click()
  await expect(page.getByRole('checkbox', { name: 'Вся леска выбрана и вся подмотка посчитана' })).not.toBeChecked()
  await page.getByRole('button', { name: 'Сохранить заброс' }).click()
  await expect(page.getByText('Заброс сохранён на этом устройстве.')).toBeVisible()
  await page.getByRole('link', { name: 'Журнал' }).click()
  await page.getByRole('button', { name: 'Открыть', exact: true }).click()
  await expect(page.getByText('Полная длина лески неизвестна: подмотка неполная.')).toBeVisible()
  await expect(page.getByText(/Падение: нет достоверного замера/)).toBeVisible()
})

for (const viewport of [{ width: 320, height: 568 }, { width: 390, height: 844 }]) {
  test(`first action fits ${viewport.width}×${viewport.height}, and direction sheet returns focus`, async ({ page }) => {
    await page.setViewportSize(viewport)
    await page.goto('./')
    const start = page.getByRole('button', { name: 'Начать промер' })
    await expect(start).toBeVisible()
    const bounds = await start.boundingBox()
    expect(bounds).not.toBeNull()
    expect(bounds!.y).toBeGreaterThanOrEqual(0)
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(viewport.height)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)

    const direction = page.locator('.survey-metric').nth(1)
    await direction.focus()
    await direction.click()
    await expect(page.getByRole('dialog')).toBeVisible()
    const angle = page.getByRole('textbox', { name: /Угол от ориентира/ })
    await expect(angle).toBeVisible()
    await angle.fill('999')
    await page.getByRole('button', { name: 'Использовать угол' }).click()
    await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Угол должен быть')
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(direction).toBeFocused()
  })
}

test('switching field modes keeps the armed draft', async ({ page }) => {
  await page.route('https://mapy.geoportal.gov.pl/**', route => route.abort())
  await page.goto('./')
  await page.getByRole('button', { name: 'Начать промер' }).click()
  await expect(page.getByRole('button', { name: 'Коснулся воды' })).toBeVisible()
  const switcher = page.getByRole('navigation', { name: 'Вид карты' })
  await switcher.getByRole('button', { name: 'Снимок' }).click()
  await expect(page.getByRole('button', { name: 'Коснулся воды' })).toBeVisible()
  await switcher.getByRole('button', { name: '3D' }).click()
  await expect(page.getByRole('button', { name: 'Коснулся воды' })).toBeVisible()
  await switcher.getByRole('button', { name: 'Сектор' }).click()
  await expect(page.getByRole('button', { name: 'Коснулся воды' })).toBeVisible()
})
